
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dilumdesilva
 */
public class SecondScreen extends javax.swing.JFrame {
    
    //String variables to hold the path of the images
    ///Users/dilumdesilva/Workspaces/IIT_Workspace/Algorithms/CW/ThirdAttempt/PathFinder/src/images/mapPic.png
    String pictureMap_path = "src/images/mapPic.png";
    String gridMap_path = "src/images/gridPic.png";
    int counterLeft = 1;
    int counterRight = 1;
    
    boolean leftPressed = false;
    boolean rightPressed = false;
    
    int selectedDistanceMetrics = 0;
    boolean rBtnEuclideanClicked, rBtnManhattanClicked, rBtnChebyshevClicked  = false;

    /**
     * Creates new form SeconScreen
     */
    public SecondScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMapImage = new javax.swing.JLabel();
        btnLeft = new javax.swing.JLabel();
        rBtnManhattan = new javax.swing.JRadioButton();
        btnRight = new javax.swing.JLabel();
        rBtnEuclidean = new javax.swing.JRadioButton();
        rBtnChebyshev = new javax.swing.JRadioButton();
        btnGenerateMap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(13, 127, 137));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please select your preference map & distance metric");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 44, -1, -1));

        lblMapImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel1.add(lblMapImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 118, -1, -1));

        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow_left.png"))); // NOI18N
        btnLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLeftMouseClicked(evt);
            }
        });
        jPanel1.add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 175, -1, -1));

        rBtnManhattan.setForeground(new java.awt.Color(255, 255, 255));
        rBtnManhattan.setText("Manhattan");
        rBtnManhattan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnManhattanActionPerformed(evt);
            }
        });
        jPanel1.add(rBtnManhattan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow_right.png"))); // NOI18N
        btnRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRightMouseClicked(evt);
            }
        });
        jPanel1.add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        rBtnEuclidean.setForeground(new java.awt.Color(255, 255, 255));
        rBtnEuclidean.setText("Euclidean");
        rBtnEuclidean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnEuclideanActionPerformed(evt);
            }
        });
        jPanel1.add(rBtnEuclidean, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        rBtnChebyshev.setForeground(new java.awt.Color(255, 255, 255));
        rBtnChebyshev.setText("Chebyshev");
        rBtnChebyshev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnChebyshevActionPerformed(evt);
            }
        });
        jPanel1.add(rBtnChebyshev, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        btnGenerateMap.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerateMap.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        btnGenerateMap.setForeground(new java.awt.Color(13, 127, 137));
        btnGenerateMap.setText("Generate");
        btnGenerateMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateMapActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerateMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 139, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateMapActionPerformed
        // once user clicks on this it will take login screen:

        //variables to capture mapType
        int mapType = 0;
        String selctedMap = lblMapImage.getIcon().toString();
        //System.out.println(lblMapImage.getIcon().toString());

        //mapType 1 - pictureMap
        //mapType 2 - gridMap

        if (selctedMap.equals(pictureMap_path)) {
            System.out.println(customColors.custom_PURPLE+"User has selected picture map"+customColors.custom_RESET);
            System.out.println("");
            mapType = 1;
        }
        else if(selctedMap.equals(gridMap_path)){
            System.out.println(customColors.custom_PURPLE+"User has selected grid map"+customColors.custom_RESET);
            System.out.println("");
            mapType = 2;
        }

        pathFinder pathFinder = new pathFinder();
        this.dispose();
        pathFinder.pathFinderMain(mapType);
    }//GEN-LAST:event_btnGenerateMapActionPerformed

    private void rBtnChebyshevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnChebyshevActionPerformed
        // TODO add your handling code here:
        rBtnEuclideanClicked = false;
        rBtnManhattanClicked = false;
        if (rBtnChebyshevClicked == false) {
            System.out.println(customColors.custom_PURPLE+"User has selected Chebyshev distance metrics"+customColors.custom_RESET);
        }

        rBtnChebyshevClicked = true;
    }//GEN-LAST:event_rBtnChebyshevActionPerformed

    private void rBtnEuclideanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnEuclideanActionPerformed
        // TODO add your handling code here:
        rBtnManhattanClicked = false;
        rBtnChebyshevClicked = false;
        if (rBtnEuclideanClicked == false) {
            System.out.println(customColors.custom_PURPLE+"User has selected Euclidean distance metrics"+customColors.custom_RESET);
        }

        rBtnEuclideanClicked = true;
    }//GEN-LAST:event_rBtnEuclideanActionPerformed

    private void btnRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRightMouseClicked
        // this method will execute ones user press on the right arrow btn
        if (rightPressed == false) {
            lblMapImage.setIcon(new ImageIcon(gridMap_path));
        }else{
            lblMapImage.setIcon(new ImageIcon(pictureMap_path));
        }

        rightPressed = true;
        leftPressed = false;
    }//GEN-LAST:event_btnRightMouseClicked

    private void rBtnManhattanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnManhattanActionPerformed
        // TODO add your handling code here
        rBtnEuclideanClicked = false;
        rBtnChebyshevClicked = false;
        if (rBtnManhattanClicked == false) {
            System.out.println(customColors.custom_PURPLE+"User has selected Manhattan distance metrics"+customColors.custom_RESET);
        }

        rBtnManhattanClicked = true;
    }//GEN-LAST:event_rBtnManhattanActionPerformed

    private void btnLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeftMouseClicked
        // this method will execute ones user press on the left arrow btn
        if (leftPressed == false) {
            lblMapImage.setIcon(new ImageIcon(pictureMap_path));
        }else{
            lblMapImage.setIcon(new ImageIcon(gridMap_path));
        }

        leftPressed = true;
        rightPressed = false;
    }//GEN-LAST:event_btnLeftMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateMap;
    private javax.swing.JLabel btnLeft;
    private javax.swing.JLabel btnRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMapImage;
    private javax.swing.JRadioButton rBtnChebyshev;
    private javax.swing.JRadioButton rBtnEuclidean;
    private javax.swing.JRadioButton rBtnManhattan;
    // End of variables declaration//GEN-END:variables
}
